name: allure-cucumber5-junit4-maven33344445555

on:
  #  push:
  #    branches-ignore:
  #      - '!master'
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:
    inputs:
      testcases_tag:
        description: 'test tag'
        default: 'prod1'
        required: true
      Env:
        description: 'this is env'
        required: true
        default: 'qas'
        type: choice
        options:
          - AAAA
          - BBBB
          - CCCC



jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: print tagname
        run: echo ${{github.event.inputs.testcases_tag || 'prod2' }}
      - uses: actions/checkout@v2


      - uses: actions/cache@v1
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: mvn dependency:go-offline compile compiler:testCompile

      - name: Run Test
        if: always()
        run: |
          if [ '${{ github.event.inputs.testcases_tag }}' == 'prod3' ] ; then
           echo ${{github.event.inputs.testcases_tag}}
           echo ${{github.event.inputs.testcases_tag || 'prod4' }}
           echo -Dspring.ENV=${{ github.event.inputs.Env || '' }}
           echo 1
           mvn test
          elif [ '${{ github.event.inputs.testcases_tag }}' == '' ] ; then
           echo ${{github.event.inputs.testcases_tag}}
           echo ${{github.event.inputs.testcases_tag || 'prod5' }}
           echo -Dspring.ENV=${{ github.event.inputs.Env || 'qas3' }}
           echo 2
           mvn test
          else
           echo ${{github.event.inputs.testcases_tag || 'prod6' }}
           echo ${{github.event.inputs.testcases_tag}}
           echo 3
           mvn package
          fi



      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages/testing
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 100

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

#      - name: Deploy
#        if: always()
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages
#          folder: ./target/allure-results # The folder the action should deploy.